Repository restic/restic, pull requests merged in 2019-11, with the labels that each got.

#2472 doc: Improve exclude/include patterns info
  doc/040_backup.rst
Labels: documentation

#2394 add description env var RESTIC_PASSWORD_COMMAND
  doc/040_backup.rst
Labels: documentation

#2310 Update documentation for contributing
  CONTRIBUTING.md
Labels: documentation, need feedback

#2368 Clarify docs for Backblaze B2 support
  doc/030_preparing_a_new_repo.rst
Labels: documentation, need feedback

#2487 diff: Fix wrong bytes reported in diff stats (#2469)
  changelog/unreleased/issue-2469
  cmd/restic/cmd_diff.go
Labels: diff, need feedback, work in progress

#2354 Doc Addition: Wasabi repo setup instructions
  doc/030_preparing_a_new_repo.rst
Labels: need feedback
